name: IG Sniper

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-ig-sniper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Tidy Go module
      run: go mod tidy

    - name: Install dependencies
      run: |
        go get "github.com/dlclark/regexp2"
        go get "github.com/gookit/color"

    - name: Build
      run: go build -o ig-sniper -v .

    - name: List directory contents
      run: ls -la

    - name: Run IG Sniper
      env:
        IG_EMAIL: ${{ secrets.IG_EMAIL }}
        IG_USERNAME: ${{ secrets.IG_USERNAME }}
        IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        IG_TARGETS: ${{ secrets.IG_TARGETS }}
        SMTP_FROM: ${{ secrets.SMTP_FROM }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        echo "Starting IG Sniper..."
        echo "IG_EMAIL: $IG_EMAIL"
        echo "IG_USERNAME: $IG_USERNAME"
        echo "IG_TARGETS: $IG_TARGETS"
        echo "SMTP_FROM: $SMTP_FROM"
        echo "SMTP_HOST: $SMTP_HOST"
        echo "SMTP_PORT: $SMTP_PORT"
        ./ig-sniper
        echo "IG Sniper execution completed."
